# Telescope Detection System Configuration

camera:
  ip: "10.0.8.18"
  username: "admin"
  password: "REDACTED"
  stream: "main"  # Options: "main" (2K) or "sub" (lower resolution)

  # Frame processing
  target_width: 1920  # Increased for better small object detection
  target_height: 1080  # Increased for better small object detection
  buffer_size: 1  # Keep at 1 for lowest latency

detection:
  # YOLOX Model configuration (Apache 2.0 license)
  # 47x faster than GroundingDINO (11-21ms vs 560ms)
  model:
    name: "yolox-s"  # YOLOX-S variant (good speed/accuracy balance)
    weights: "models/yolox/yolox_s.pth"
  device: "cuda:0"

  # YOLOX input size (larger = better for small objects, but slower)
  # 640x640: ~11-21ms (fast, standard)
  # 1280x1280: ~50-100ms (slower, better for small/distant wildlife)
  # 1920x1920: ~150-250ms (slow, maximum detail for tiny IR wildlife)
  input_size: [1920, 1920]  # [height, width]

  # YOLOX detection thresholds
  conf_threshold: 0.15  # Confidence threshold (low for small wildlife, but not too aggressive)
  nms_threshold: 0.45   # NMS IoU threshold
  wildlife_only: true   # Filter to wildlife-relevant classes only

  # Legacy prompts (not used by YOLOX, kept for reference)
  # YOLOX detects 80 COCO classes including: person, bird, cat, dog, horse, sheep, cow, bear, etc.
  text_prompts:
    # Humans and pets
    - "person"
    - "dog"
    - "cat"

    # Desert mammals (predators)
    - "coyote"
    - "bobcat"
    - "fox"
    - "mountain lion"
    - "puma"
    - "skunk"
    - "raccoon"

    # Desert mammals (prey/herbivores)
    - "rabbit"
    - "cottontail"
    - "jackrabbit"
    - "ground squirrel"
    - "pack rat"
    - "kangaroo rat"
    - "mouse"
    - "deer"
    - "mule deer"
    - "javelina"
    - "peccary"

    # Birds (raptors)
    - "hawk"
    - "red-tailed hawk"
    - "owl"
    - "great horned owl"
    - "barn owl"
    - "falcon"
    - "kestrel"
    - "vulture"
    - "turkey vulture"
    - "eagle"

    # Birds (ground dwellers)
    - "roadrunner"
    - "quail"
    - "gambel's quail"

    # Birds (common)
    - "raven"
    - "crow"
    - "dove"
    - "mourning dove"
    - "hummingbird"
    - "sparrow"
    - "finch"
    - "jay"
    - "woodpecker"
    - "thrush"
    - "mockingbird"
    - "cardinal"
    - "oriole"

    # Reptiles (lizards)
    - "lizard"
    - "desert lizard"
    - "small lizard"
    - "iguana"
    - "desert iguana"
    - "chuckwalla"
    - "collared lizard"
    - "horned lizard"
    - "gecko"
    - "zebra-tailed lizard"

    # Reptiles (snakes and tortoises)
    - "snake"
    - "rattlesnake"
    - "gopher snake"
    - "king snake"
    - "tortoise"
    - "desert tortoise"

    # Amphibians
    - "toad"
    - "frog"

    # Arthropods (if visible at distance)
    - "scorpion"
    - "tarantula"

    # General categories (fallback)
    - "reptile"
    - "bird"
    - "mammal"
    - "small animal"

  # Two-stage detection pipeline (YOLOX + iNaturalist)
  use_two_stage: true  # Enable Stage 2 species classification
  enable_species_classification: true  # Enable fine-grained species ID

  # Per-class confidence overrides (higher threshold = fewer false positives)
  class_confidence_overrides:
    person: 0.60  # Much higher to reduce false "person" detections
    bird: 0.55    # High threshold - telescope covers falsely detected as birds
    bear: 0.70    # Very high - bears extremely rare in Mojave, rocks often misdetected

  # Size filtering (better than just confidence for distant wildlife!)
  # Note: Inference runs at 1920x1920 (3,686,400 total pixels)
  # Typical sizes at this resolution: tiny=50-200px², small bird/rabbit=200-1000px², coyote=1000-5000px²
  min_box_area: 20  # Minimum bounding box area in pixels² (~4.5x4.5 pixels) - catches very small/distant animals
  max_detections: 300  # Maximum number of detections per frame

# Stage 2 Species Classification (fine-grained identification)
species_classification:
  enabled: true
  confidence_threshold: 0.3  # Minimum confidence for species ID

  # Universal iNaturalist model (covers 10,000 species)
  inat_classifier:
    model_name: "timm/eva02_large_patch14_clip_336.merged2b_ft_inat21"
    taxonomy_file: "models/inat2021_taxonomy.json"  # Full taxonomy with hierarchical data
    input_size: 336  # EVA02 uses 336x336 input
    confidence_threshold: 0.3
    use_hierarchical: true  # Enable taxonomic fallback (genus, family, order, class)
    # Hierarchical thresholds:
    #   >= 0.5: Species (e.g., "Desert Cottontail")
    #   >= 0.4: Genus (e.g., "Sylvilagus")
    #   >= 0.3: Family (e.g., "Leporidae")
    #   >= 0.2: Order (e.g., "Lagomorpha")
    #   >= 0.1: Class (e.g., "Mammalia", "Aves", "Reptilia")

  # Image enhancement (pre-process crops before classification)
  # Improves accuracy on IR/night vision, small/distant animals
  enhancement:
    enabled: true
    method: "realesrgan"  # Options: "none", "clahe", "realesrgan"

    # Real-ESRGAN settings (4x super-resolution upscaling)
    # Speed: ~500ms-1s per crop on A30 GPU
    # Benefits: Makes small/distant wildlife visible for classification
    realesrgan:
      model_path: "models/enhancement/RealESRGAN_x4plus.pth"
      scale: 4  # Upscaling factor (2, 3, or 4)
      tile: 512  # Process in tiles (0 = no tiling, larger = faster but more VRAM)
      tile_pad: 10  # Padding for tiles to avoid edge artifacts
      half: false  # Use FP16 for 2x speedup (may reduce quality slightly)
      # Note: device is inherited from detection.device (main GPU/CPU setting)

    # CLAHE settings (contrast enhancement)
    # Fast (~5ms), improves low-contrast night vision images
    clahe:
      clip_limit: 2.0  # Higher = more contrast (1.0-4.0 typical)
      tile_grid_size: [8, 8]  # Tile grid for adaptive histogram equalization

    # Bilateral filter settings (denoising while preserving edges)
    # Fast (~10ms), reduces noise in IR images
    bilateral:
      d: 9  # Filter diameter (larger = stronger but slower)
      sigma_color: 75  # Color space sigma (higher = more colors considered similar)
      sigma_space: 75  # Coordinate space sigma (higher = larger neighborhood)

web:
  host: "0.0.0.0"
  port: 8000

performance:
  # Queue sizes
  frame_queue_size: 2
  detection_queue_size: 10

  # Detection history
  history_size: 30

# Future configuration for Phase 3
detection_zones: []
  # Example:
  # - name: "telescope_danger_zone"
  #   type: "polygon"
  #   points: [[100,200], [300,200], [300,400], [100,400]]
  #   alert_on_entry: ["person"]

collision_detection:
  enabled: false
  danger_threshold: 50  # pixels

# Snapshot/Clip Saving
snapshots:
  enabled: true  # Enable snapshot saving
  save_mode: "image"  # "image" for single frames, "clip" for videos
  output_dir: "clips"  # Directory to save snapshots

  # Trigger settings
  trigger_classes:  # Classes that trigger saves (empty = all detections)
    - "person"
    - "cat"      # might catch: iguanas, large lizards
    - "dog"      # might catch: coyotes
    - "bird"     # will catch: roadrunner, quail, all birds
    # Wildlife-adjacent that might be relevant:
    - "bear"
    - "horse"
    - "sheep"
    - "cow"
    # Note: bananas, chairs, potted plants, etc. will still DISPLAY but won't save snapshots!
  min_confidence: 0.30  # Lower for distant/small wildlife from high camera mount
  cooldown_seconds: 45  # Seconds between saves for same class
  save_annotated: true  # Save with bounding boxes drawn

  # Video clip settings (only used if save_mode="clip")
  clip_duration: 10  # Total clip duration in seconds
  pre_buffer_seconds: 5  # Seconds of video before detection
  fps: 30  # Frames per second for video clips
